In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 4 dimensions for each word
import math
def positionalEncodings(sequence):
    
    PE=[]
    d_model=4
    for pos in range(sequence):
        EncodingsOfEach=[]
        for i in range(d_model):
            if i%2==0:
                temp=pos/(math.pow(10000,(2*i)/d_model))
                EncodingsOfEach.append(math.sin(temp))
            else:
                temp=pos/(math.pow(10000,(2*(i-1))/d_model))
                EncodingsOfEach.append(math.cos(temp))
        PE.append(EncodingsOfEach)
    return PE

In [3]:
def selfAttention(embeddings, W_q, W_k, W_v):
    numberOfWords = tf.shape(embeddings)[0]

    Q, K, V = [], [], []
    for i in range(numberOfWords):
        x_i = tf.expand_dims(embeddings[i], 0)
        Q.append(tf.matmul(x_i, W_q))
        K.append(tf.matmul(x_i, W_k))
        V.append(tf.matmul(x_i, W_v))

    d_k = tf.math.sqrt(tf.cast(tf.shape(K[0])[1], tf.float32))

    attention_outputs = []

    for i in range(numberOfWords):
        score_list = []
        for j in range(numberOfWords):
            score = tf.matmul(Q[i], K[j], transpose_b=True)[0, 0] / d_k
            score_list.append(score)

        scores = tf.stack(score_list)
        weights = tf.nn.softmax(scores)

        output = tf.zeros_like(V[0])
        for j in range(numberOfWords):
            output += weights[j] * V[j]

        attention_outputs.append(output[0])

    return tf.stack(attention_outputs)


In [4]:
def Add_and_normalize(output_of_previous,input_of_previous):
    layer_norm = tf.keras.layers.LayerNormalization(epsilon=1e-6)
    return layer_norm(output_of_previous + input_of_previous)

In [5]:
def FeedForwardNN(x, W1, b1, W2, b2):
    hidden = tf.nn.relu(tf.matmul(x, W1) + b1)
    out = tf.matmul(hidden, W2) + b2
    return out


In [6]:
def Encoder(positional_encodings_plus_embeddings,W_q,W_k,W_v,W1,b1,W2,b2):
    self_attn_output=selfAttention(positional_encodings_plus_embeddings,W_q,W_k,W_v)
    add_and_normalize_1_output=Add_and_normalize(self_attn_output,positional_encodings_plus_embeddings)
    ffn_output=FeedForwardNN(add_and_normalize_1_output,W1,b1,W2,b2)
    encoder_output=Add_and_normalize(ffn_output,add_and_normalize_1_output)
    return encoder_output

In [7]:
embeddings=tf.constant([[1,0,1,0],[0,1,0,1],[1,1,1,1]],dtype=tf.float32)
positional_encodings=positionalEncodings(len(embeddings))
embeddings_plus_PE=embeddings+positional_encodings
d_model=embeddings_plus_PE[0].shape[0]
encoder_params = []
for _ in range(6):
    params = {
        "W_q": tf.Variable(tf.random.normal(shape=(d_model,d_model))),
        "W_k": tf.Variable(tf.random.normal(shape=(d_model,d_model))),
        "W_v": tf.Variable(tf.random.normal(shape=(d_model,d_model))),
        "W1": tf.Variable(tf.random.normal(shape=(d_model,256))),
        "b1": tf.Variable(tf.random.normal(shape=(256,))),
        "W2": tf.Variable(tf.random.normal(shape=(256,d_model))),
        "b2": tf.Variable(tf.random.normal(shape=(d_model,)))
    }
    encoder_params.append(params)


In [8]:
def encoderStack(x, encoder_params):
    for layer in encoder_params:
        x = Encoder(
            x,
            layer["W_q"],
            layer["W_k"],
            layer["W_v"],
            layer["W1"],
            layer["b1"],
            layer["W2"],
            layer["b2"]
        )
    return x


In [9]:
encoder_output=(encoderStack(embeddings_plus_PE,encoder_params))

In [10]:
encoder_output

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.3913472 ,  0.6703489 , -0.46256405,  1.1835624 ],
       [-1.3935652 ,  0.6702541 , -0.45905954,  1.1823704 ],
       [-1.3927484 ,  0.67031825, -0.46036035,  1.1827906 ]],
      dtype=float32)>

Decoder:


In [11]:
def masked_Attention(embeddings, W_q, W_k, W_v,mask):
    numberOfWords = tf.shape(embeddings)[0]

    Q, K, V = [], [], []
    for i in range(numberOfWords):
        x_i = tf.expand_dims(embeddings[i], 0)
        Q.append(tf.matmul(x_i, W_q))
        K.append(tf.matmul(x_i, W_k))
        V.append(tf.matmul(x_i, W_v))

    d_k = tf.math.sqrt(tf.cast(tf.shape(K[0])[1], tf.float32))

    attention_outputs = []

    for i in range(numberOfWords):
        score_list = []
        for j in range(numberOfWords):
            score = tf.matmul(Q[i], K[j], transpose_b=True)[0, 0] / d_k
            score=score+mask[i][j]
            score_list.append(score)

        scores = tf.stack(score_list)
        weights = tf.nn.softmax(scores)

        output = tf.zeros_like(V[0])
        for j in range(numberOfWords):
            output += weights[j] * V[j]

        attention_outputs.append(output[0])

    return tf.stack(attention_outputs)


In [12]:
def Encoder_decoder_attention(encoder_output,prev_layer_output,W_q,W_k,W_v):
    numberOfWords = tf.shape(encoder_output)[0]

    Q, K, V = [], [], []
    for i in range(numberOfWords):
        q_i = tf.expand_dims(prev_layer_output[i], 0)
        enc_i = tf.expand_dims(encoder_output[i], 0)
        Q.append(tf.matmul(q_i, W_q))
        K.append(tf.matmul(enc_i, W_k))
        V.append(tf.matmul(enc_i, W_v))

    d_k = tf.math.sqrt(tf.cast(tf.shape(K[0])[1], tf.float32))

    attention_outputs = []

    for i in range(numberOfWords):
        score_list = []
        for j in range(numberOfWords):
            score = tf.matmul(Q[i], K[j], transpose_b=True)[0, 0] / d_k
            score_list.append(score)

        scores = tf.stack(score_list)
        weights = tf.nn.softmax(scores)

        output = tf.zeros_like(V[0])
        for j in range(numberOfWords):
            output += weights[j] * V[j]

        attention_outputs.append(output[0])

    return tf.stack(attention_outputs)
    

In [13]:
def decoder(positional_encodings_plus_embeddings,encoder_output,W_q_self,W_k_self,W_v_self,W_q_cross,W_k_cross,W_v_cross,mask,W1,b1,W2,b2):
    masked_self_attn_output=masked_Attention(positional_encodings_plus_embeddings,W_q_self,W_k_self,W_v_self,mask)
    add_and_normalize_1_output=Add_and_normalize(masked_self_attn_output,positional_encodings_plus_embeddings)
    encoder_decoder_attn_output=Encoder_decoder_attention(encoder_output,add_and_normalize_1_output,W_q_cross,W_k_cross,W_v_cross)
    add_and_normalize_2_output=Add_and_normalize(encoder_decoder_attn_output,add_and_normalize_1_output)
    ffn_output=FeedForwardNN(add_and_normalize_2_output,W1,b1,W2,b2)
    decoder_output=Add_and_normalize(ffn_output,add_and_normalize_2_output)
    return decoder_output

In [14]:
def causal_mask(d):
    mask = tf.linalg.band_part(tf.ones((d, d)), -1, 0)
    return (1.0 - mask) * -1e9


In [15]:
d_model=embeddings_plus_PE[0].shape[0]
mask=causal_mask(d_model)
decoder_params = []

for _ in range(6):
    params = {
        "W_q_self": tf.Variable(tf.random.normal(shape=(d_model,d_model))),
        "W_k_self": tf.Variable(tf.random.normal(shape=(d_model,d_model))),
        "W_v_self": tf.Variable(tf.random.normal(shape=(d_model,d_model))),
        "W_q_cross": tf.Variable(tf.random.normal(shape=(d_model,d_model))),
        "W_k_cross": tf.Variable(tf.random.normal(shape=(d_model,d_model))),
        "W_v_cross": tf.Variable(tf.random.normal(shape=(d_model,d_model))),
        "W1": tf.Variable(tf.random.normal(shape=(d_model,256))),
        "b1": tf.Variable(tf.random.normal(shape=(256,))),
        "W2": tf.Variable(tf.random.normal(shape=(256,d_model))),
        "b2": tf.Variable(tf.random.normal(shape=(d_model,)))
    }
    decoder_params.append(params)

In [16]:
def decoderStack(x,decoder_params,encoder_output):
    for layer in decoder_params:
        x=decoder(x,encoder_output,layer["W_q_self"],layer["W_k_self"],layer["W_v_self"],layer["W_q_cross"],layer["W_k_cross"],layer["W_v_cross"],mask,layer["W1"],layer["b1"],layer["W2"],layer["b2"])
    return x

In [17]:
embeddings=tf.constant([[1,0,1,0],[0,1,1,0],[1,1,0,1]],dtype=tf.float32)
positional_encodings=positionalEncodings(len(embeddings))
embeddings_plus_PE=embeddings+positional_encodings

In [18]:
print(decoderStack(embeddings_plus_PE,decoder_params,encoder_output))

tf.Tensor(
[[ 0.83228827 -1.6974741   0.27196252  0.59322333]
 [ 0.8322718  -1.6974778   0.2719764   0.59322953]
 [ 0.8322394  -1.6974734   0.27192146  0.59331256]], shape=(3, 4), dtype=float32)
